cnpm install -g webpack

cnpm install --save-dev babel-core
cnpm install --save-dev babel-loader
cnpm install --save-dev babel-preset-es2015
cnpm install --save-dev babel-preset-react
cnpm install --save-dev babel-preset-react-hmre
cnpm install --save-dev babel-register
cnpm install --save-dev cross-env
cnpm install --save-dev css-loader
cnpm install --save-dev expect
cnpm install --save-dev express
cnpm install --save-dev gulp
cnpm install --save-dev jsdom
cnpm install --save-dev jsx-loader
cnpm install --save-dev less
cnpm install --save-dev less-loader
cnpm install --save-dev mocha
cnpm install --save-dev node-libs-browser
cnpm install --save-dev raw-loader
cnpm install --save-dev react-addons-test-utils
cnpm install --save-dev react-hot-loader
cnpm install --save-dev redux-devtools
cnpm install --save-dev style-loader
cnpm install --save-dev webpack
cnpm install --save-dev webpack-dev-middleware
cnpm install --save-dev webpack-dev-server
cnpm install --save-dev webpack-hot-middleware